# Generated by Django 2.2.18 on 2022-10-11 09:47

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('datahub', '0006_datasource_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_at', models.DateTimeField(auto_now=True)),
                ('reading_rank', models.IntegerField(default=0)),
                ('article_count', models.IntegerField(default=0)),
                ('last_read_datetime', models.DateTimeField(blank=True, null=True)),
                ('avg_reading_progress', models.FloatField(default=0)),
                ('clientbase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_info', to='team.ClientBase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.TextField()),
                ('removed', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_at', models.DateTimeField(auto_now=True)),
                ('value_tag_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(default='', max_length=256)),
                ('name', models.CharField(default='', max_length=512)),
                ('removed', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
                ('attributions', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('categories', models.ManyToManyField(blank=True, to='retail.ProductCategory')),
                ('datasource', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datahub.DataSource')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['team'], name='retail_prod_team_id_bcc14d_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name'], name='retail_prod_name_97c2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['team', 'name'], name='retail_prod_team_id_511206_idx'),
        ),
        migrations.AddIndex(
            model_name='productbase',
            index=models.Index(fields=['datasource'], name='retail_prod_datasou_6c8878_idx'),
        ),
        migrations.AddIndex(
            model_name='productbase',
            index=models.Index(fields=['team', 'datasource'], name='retail_prod_team_id_009047_idx'),
        ),
    ]
