# Generated by Django 2.2.18 on 2022-10-12 06:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0006_datasource_website'),
        ('team', '0001_initial'),
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('external_id', models.CharField(max_length=256)),
                ('datetime', models.DateTimeField()),
                ('total_price', models.FloatField(default=0)),
                ('attributions', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('status', models.CharField(default='CONFIRMED', max_length=64)),
                ('categories', models.ManyToManyField(blank=True, to='retail.ProductCategory')),
                ('clientbase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.ClientBase')),
                ('datasource', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datahub.DataSource')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_at', models.DateTimeField(auto_now=True)),
                ('datalist_id', models.IntegerField(blank=True, null=True)),
                ('refound', models.BooleanField(default=False)),
                ('sale_price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.FloatField(default=0.0)),
                ('clientbase', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.ClientBase')),
                ('productbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.ProductBase')),
                ('purchasebase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.PurchaseBase')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.AddIndex(
            model_name='purchasebase',
            index=models.Index(fields=['datasource'], name='retail_purc_datasou_803f46_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebase',
            index=models.Index(fields=['team', 'datasource'], name='retail_purc_team_id_70ca29_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['team'], name='retail_orde_team_id_ed6806_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['productbase'], name='retail_orde_product_e7f8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['purchasebase'], name='retail_orde_purchas_db9149_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['clientbase'], name='retail_orde_clientb_2e0759_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['team', 'productbase'], name='retail_orde_team_id_3b9ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['team', 'purchasebase'], name='retail_orde_team_id_c6be46_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['team', 'clientbase'], name='retail_orde_team_id_b0f5b6_idx'),
        ),
    ]
