# Generated by Django 2.2.18 on 2022-10-21 05:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('from_level_id', models.TextField()),
                ('to_level_id', models.TextField()),
                ('clientbase_external_id', models.TextField()),
                ('datetime', models.DateTimeField(null=True)),
                ('from_datetime', models.DateTimeField(null=True)),
                ('to_datetime', models.DateTimeField(null=True)),
                ('source_type', models.CharField(max_length=128)),
                ('attributions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('datalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importly.DataList')),
                ('datalistrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importly.DataListRow')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahub.DataSource')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('external_id', models.TextField()),
                ('rank', models.IntegerField(default=0)),
                ('name', models.TextField()),
                ('attributions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('datalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importly.DataList')),
                ('datalistrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importly.DataListRow')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahub.DataSource')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('event_external_id', models.TextField()),
                ('clientbase_external_id', models.TextField()),
                ('datetime', models.DateTimeField(null=True)),
                ('action', models.CharField(choices=[('claim', '領取'), ('use', '使用')], default='claim', max_length=64)),
                ('attributions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('datalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importly.DataList')),
                ('datalistrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importly.DataListRow')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahub.DataSource')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('external_id', models.TextField()),
                ('name', models.TextField()),
                ('ticket_type', models.TextField()),
                ('ticket_name', models.TextField()),
                ('cost_type', models.CharField(choices=[('free', '免費'), ('code', '兌換碼'), ('credit', '點數')], default='free', max_length=64)),
                ('attributions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('datalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importly.DataList')),
                ('datalistrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importly.DataListRow')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahub.DataSource')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.AddIndex(
            model_name='levellog',
            index=models.Index(fields=['datalistrow'], name='wish_import_datalis_a96082_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['team'], name='wish_import_team_id_510d74_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['name'], name='wish_import_name_1d8f77_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['team', 'name'], name='wish_import_team_id_02a4f3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['datalistrow'], name='wish_import_datalis_9e519e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['cost_type'], name='wish_import_cost_ty_491124_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['ticket_type'], name='wish_import_ticket__b35fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['ticket_type', 'cost_type'], name='wish_import_ticket__0c3c90_idx'),
        ),
    ]
