# Generated by Django 2.2.18 on 2022-10-21 07:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('wish_importly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='external_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='levellog',
            name='external_id',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('point_name', models.TextField()),
                ('clientbase_external_id', models.TextField()),
                ('datetime', models.DateTimeField(null=True)),
                ('amount', models.IntegerField(default=0)),
                ('is_transaction', models.BooleanField(default=False)),
                ('attributions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('datalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importly.DataList')),
                ('datalistrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importly.DataListRow')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='pointlog',
            index=models.Index(fields=['datalistrow'], name='wish_import_datalis_8131e2_idx'),
        ),
    ]
