# Generated by Django 2.2.18 on 2022-10-11 09:47

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datahub', '0006_datasource_website'),
        ('team', '0001_initial'),
        ('importly', '0001_initial'),
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('author', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('path', models.CharField(max_length=256)),
                ('status', models.CharField(default=str, max_length=64)),
                ('removed', models.BooleanField(default=False)),
                ('attributions', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), default=list, size=None)),
                ('datalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importly.DataList')),
                ('datalistrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importly.DataListRow')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahub.DataSource')),
                ('productbase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.ProductBase')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['team'], name='retail_impo_team_id_28cdfa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['datasource'], name='retail_impo_datasou_f3b91d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='retail_impo_title_ce73ef_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['team', 'datasource'], name='retail_impo_team_id_4297db_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['team', 'title'], name='retail_impo_team_id_e5f238_idx'),
        ),
    ]
