# Generated by Django 2.2.18 on 2022-10-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_importly', '0002_auto_20221012_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrow',
            name='productbase_id',
            field=models.IntegerField(default=1),
        ),
    ]
