# Generated by Django 2.2.18 on 2022-10-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_auto_20221012_1411'),
        ('retail_importly', '0004_auto_20221012_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchasebase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.PurchaseBase'),
        ),
    ]
